apiVersion: apps/v1
kind: Deployment
metadata:
  name: documenso
  namespace: documenso
  labels:
    app: documenso
spec:
  replicas: 2
  # 불필요한 RS 누적 방지(원래 10이었다면 유지해도 무방)
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: documenso
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: documenso
    spec:
      containers:
        - name: web
          # ✅ latest 제거 → 불변 다이제스트로 고정
          image: 348823728620.dkr.ecr.ap-northeast-2.amazonaws.com/documenso@sha256:cd7c7150491d6da8e54c122446bec567ebc48cf50d0a573813237eaa36a92904
          # 다이제스트는 IfNotPresent로 충분 (latest가 아니니 Always 불필요)
          imagePullPolicy: IfNotPresent

          # remix만 실행
          workingDir: /app/apps/remix
          command: ["npm"]
          args: ["run", "start"]

          ports:
            - name: http
              containerPort: 3000

          # 헬스 체크
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 1
            failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "1"
              memory: "1Gi"

          # ALB DNS (현재 값 유지)
          env:
            - name: NEXTAUTH_URL
              value: "http://k8s-documens-documens-a6bf42ff50-1816123568.ap-northeast-2.elb.amazonaws.com"
            - name: NEXT_PUBLIC_WEBAPP_URL
              value: "http://k8s-documens-documens-a6bf42ff50-1816123568.ap-northeast-2.elb.amazonaws.com"
            - name: NEXT_PRIVATE_INTERNAL_WEBAPP_URL
              value: "http://localhost:3000"
            - name: APP_URL
              value: "http://k8s-documens-documens-a6bf42ff50-1816123568.ap-northeast-2.elb.amazonaws.com"

            # DB 시크릿
            - name: NEXT_PRIVATE_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: documenso-db
                  key: NEXT_PRIVATE_DATABASE_URL
            - name: NEXT_PRIVATE_DIRECT_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: documenso-db
                  key: NEXT_PRIVATE_DIRECT_DATABASE_URL
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: documenso-db
                  key: DATABASE_URL

            # SMTP/EMAIL 시크릿
            - name: EMAIL_FROM
              valueFrom:
                secretKeyRef:
                  name: documenso-smtp
                  key: EMAIL_FROM
            - name: EMAIL_SERVER_HOST
              valueFrom:
                secretKeyRef:
                  name: documenso-smtp
                  key: EMAIL_SERVER_HOST
            - name: EMAIL_SERVER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: documenso-smtp
                  key: EMAIL_SERVER_PASSWORD
            - name: EMAIL_SERVER_PORT
              valueFrom:
                secretKeyRef:
                  name: documenso-smtp
                  key: EMAIL_SERVER_PORT
            - name: EMAIL_SERVER_USER
              valueFrom:
                secretKeyRef:
                  name: documenso-smtp
                  key: EMAIL_SERVER_USER
            - name: SMTP_FROM
              valueFrom:
                secretKeyRef:
                  name: documenso-smtp
                  key: SMTP_FROM
            - name: SMTP_HOST
              valueFrom:
                secretKeyRef:
                  name: documenso-smtp
                  key: SMTP_HOST
            - name: SMTP_PORT
              valueFrom:
                secretKeyRef:
                  name: documenso-smtp
                  key: SMTP_PORT
            - name: SMTP_PASS
              valueFrom:
                secretKeyRef:
                  name: documenso-smtp
                  key: SMTP_PASS
            - name: SMTP_USER
              valueFrom:
                secretKeyRef:
                  name: documenso-smtp
                  key: SMTP_USER

          # 통짜 환경 시크릿 유지
          envFrom:
            - secretRef:
                name: documenso-env
      restartPolicy: Always
