name: Build -> Push ECR -> PR to k8s repo

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  id-token: write

env:
  AWS_REGION: ap-northeast-2
  ECR_REPOSITORY: documenso
  K8S_DEPLOYMENT_FILE: k8s/documenso/deployment.yaml
  K8S_CONTAINER_NAME: web
  PR_BRANCH_PREFIX: bump-image-

jobs:
  build-and-pr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true   # ← 같은 레포에 push할 거라 true

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Define image info
        id: vars
        run: echo "IMAGE_URI=${{ steps.ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${GITHUB_SHA}" >> $GITHUB_OUTPUT

      - name: Build & Push
        env:
          IMAGE_URI: ${{ steps.vars.outputs.IMAGE_URI }}
        run: |
          docker build --platform linux/amd64 -t "$IMAGE_URI" .
          docker push "$IMAGE_URI"

      - name: Install yq
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq

      - name: Create bump branch
        env:
          BRANCH: ${{ env.PR_BRANCH_PREFIX }}${{ github.sha }}
        run: |
          git checkout -b "$BRANCH"

      - name: Update image in deployment.yaml
        env:
          FILE: ${{ env.K8S_DEPLOYMENT_FILE }}
          CONTAINER: ${{ env.K8S_CONTAINER_NAME }}
          IMAGE_URI: ${{ steps.vars.outputs.IMAGE_URI }}
        run: |
          yq -i '(.spec.template.spec.containers[] | select(.name == env(CONTAINER)) .image) = env(IMAGE_URI)' "$FILE"
          git --no-pager diff "$FILE" || true

      - name: Commit changes
        env:
          BRANCH: ${{ env.PR_BRANCH_PREFIX }}${{ github.sha }}
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add ${{ env.K8S_DEPLOYMENT_FILE }}
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "chore(k8s): bump image to ${{ steps.vars.outputs.IMAGE_URI }}"
          git push --set-upstream origin "$BRANCH"

      - name: Open PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: ${{ env.PR_BRANCH_PREFIX }}${{ github.sha }}
        run: |
          gh pr create \
            --title "chore(k8s): bump image to ${{ steps.vars.outputs.IMAGE_URI }}" \
            --body "Automated PR from app build." \
            --base "main" \
            --head "$BRANCH" || echo "PR already exists or no changes."
